#!/bin/bash

# Simple counter based for loop example
echo -n "for loop counter:"
for ((i=0; i<=10;i++)) do
	echo -n " $i"
done

# Iterating from 0 to 10 using seq
echo -n -e "\\n\\nfor loop using seq:"
for i in `seq 0 1 10`; do
	echo -n " $i"
done

# Iterating from 0 to 10 using brace expansion
echo -n -e "\\n\\nfor loop using brace expansion:"
for i in {0..10}; do
	echo -n " $i"
done

# Iterating list
echo -n -e "\\n\\nIterating list by:"
for i in individually specifying items of list; do
	echo -n " $i"
done

# Nested for loop
# 2d array creation taken from http://stackoverflow.com/a/16487733/3946664
declare -a array_2d
rows=3
columns=4

for ((i=0; i<rows; i++)) do
	for ((j=0; j<columns; j++)) do
		let "array_2d[$i, $j]=$RANDOM % 10"
	done
done

echo -e "\\n\\nNested for loop: 2D array elements"
for ((i=0; i<rows; i++)) do
	for ((j=0; j<columns; j++)) do
		echo -n "${array_2d[$i, $j]} "
	done
	echo
done

# Iterating through a list generated by a command
echo -e "\\nList of files and their types in this directory:"
for i in $(ls -a); do
	# check for file type taken from http://stackoverflow.com/a/4665080/3946664
	if [[ -d $i ]]; then
		echo "$i is a directory"
	elif [[ -f $i ]]; then
		echo "$i is a file"
	else
		echo "$i is invalid"
	fi
done 